### ISSUE TITLE
Dynamic programming bottom up solution issue

### ISSUE THREAD

**Issue by chaitanya0411** [cormacpayne/Data-Structures-and-Algorithms#1]
if ( weight[ i ] >= j ) condition I think is not required or else the entries for the ith row will be zero and propogated wrongly thereafter.
Please correct me if I am wrong

**Comment by cormacpayne** [comment]
@chaitanya0411 good catch! I changed the condition to `if ( weight[ i ] <= j )` because we have an item whose weight is less than (or equal to) the current capacity, so we see if taking it or ignoring it gives us more value for that given item and capacity :smile:

**Comment by chaitanya0411** [comment]
Thanks ! :+1:
